package com.rewards.checkout.service;

import com.rewards.checkout.config.RewardProperties;
import com.rewards.checkout.domain.entity.Coupon;
import com.rewards.checkout.repository.CouponRepository;
import com.rewards.checkout.repository.OrderRepository;
import java.util.Optional;
import java.util.UUID;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * Milestone coupon generation. Exactly-once generation per milestone is guaranteed by the
 * UNIQUE(milestone_number) database constraint, not by locking: when two concurrent order
 * completions both race to generate the same milestone's coupon, there is no existing row to
 * lock (the coupon doesn't exist yet), so the constraint is the only thing that can arbitrate
 * the race. The loser's saveAndFlush throws DataIntegrityViolationException, which propagates
 * out of this REQUIRES_NEW transaction (rolling it back cleanly) for the caller to catch and
 * treat as "already generated by a concurrent transaction" - safe to ignore.
 */
@Service
public class RewardMilestoneService {

    private final OrderRepository orderRepository;
    private final CouponRepository couponRepository;
    private final RewardProperties rewardProperties;

    public RewardMilestoneService(OrderRepository orderRepository, CouponRepository couponRepository,
                                   RewardProperties rewardProperties) {
        this.orderRepository = orderRepository;
        this.couponRepository = couponRepository;
        this.rewardProperties = rewardProperties;
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public Optional<Coupon> evaluateAndGenerateIfDue() {
        long totalOrders = orderRepository.count();
        long milestone = totalOrders / rewardProperties.everyNthOrder();
        if (milestone == 0 || couponRepository.existsByMilestoneNumber(milestone)) {
            return Optional.empty();
        }
        Coupon coupon = new Coupon(generateCode(milestone), rewardProperties.discountPercent(), milestone);
        couponRepository.saveAndFlush(coupon);
        return Optional.of(coupon);
    }

    private String generateCode(long milestone) {
        return "MILESTONE-" + milestone + "-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
    }
}
